
import Classes.UtilClass;
import java.awt.Color;
import static java.lang.Thread.sleep;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 6487
 */
public class jF_Cronometro extends javax.swing.JFrame {

    /**
     * Creates new form jF_Cronometro
     */
    static int millisenconds = 0;
    static int seconds = 0;
    static int minutes = 0;
    static int hour = 0;

    Color corFundo = new Color(153, 51, 0);
    Color corLetras = new Color(255, 153, 0);

    static boolean state = true;

    int tema;
    UtilClass utilitario = new UtilClass();

    public jF_Cronometro() {
        initComponents();
    }

    
    public String verificaNumero(int intEntrada) {
        String numeroSaida;
        if (0 >= intEntrada || intEntrada <= 9) {
            numeroSaida = "0" + Integer.toString(intEntrada);
            return numeroSaida;
        } else {
            return numeroSaida = Integer.toString(intEntrada);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnMenu = new javax.swing.JButton();
        jBtnRelogio = new javax.swing.JButton();
        jBtnAjuda = new javax.swing.JButton();
        jBtnSaida = new javax.swing.JButton();
        jLblsegundo = new javax.swing.JLabel();
        jLblhora1 = new javax.swing.JLabel();
        jLblmili = new javax.swing.JLabel();
        jLblminuto2 = new javax.swing.JLabel();
        jBtnReset = new javax.swing.JButton();
        jBtnStart = new javax.swing.JButton();
        jBtnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnMenu.setText("Menu");
        jBtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 260, 114, 43));

        jBtnRelogio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnRelogio.setText("Relógio");
        jBtnRelogio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRelogioActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRelogio, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 260, 114, 43));

        jBtnAjuda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnAjuda.setText("Ajuda");
        jBtnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAjudaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 260, 114, 43));

        jBtnSaida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnSaida.setText("Saída");
        jBtnSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSaidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSaidaMouseExited(evt);
            }
        });
        jBtnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaidaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 260, 114, 43));

        jLblsegundo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLblsegundo.setText("00 : ");
        jPanel1.add(jLblsegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLblhora1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLblhora1.setText("00 : ");
        jPanel1.add(jLblhora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLblmili.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLblmili.setText("00 : ");
        jPanel1.add(jLblmili, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLblminuto2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLblminuto2.setText("00 : ");
        jPanel1.add(jLblminuto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jBtnReset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 130, 50));

        jBtnStart.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnStart.setText("Start");
        jBtnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnStartMouseExited(evt);
            }
        });
        jBtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStartActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 130, 50));

        jBtnStop.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnStop.setText("Stop");
        jBtnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnStopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnStopMouseExited(evt);
            }
        });
        jBtnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStopActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void setThemeDark() {

        jPanel1.setBackground(Color.DARK_GRAY);
        jPanel1.setForeground(Color.LIGHT_GRAY);

        jLblhora1.setForeground(Color.LIGHT_GRAY);
        jLblmili.setForeground(Color.LIGHT_GRAY);
        jLblminuto2.setForeground(Color.LIGHT_GRAY);
        jLblsegundo.setForeground(Color.LIGHT_GRAY);

        jBtnMenu.setBackground(Color.DARK_GRAY);
        jBtnMenu.setForeground(Color.LIGHT_GRAY);

        jBtnRelogio.setBackground(Color.DARK_GRAY);
        jBtnRelogio.setForeground(Color.LIGHT_GRAY);

        jBtnAjuda.setBackground(Color.DARK_GRAY);
        jBtnAjuda.setForeground(Color.LIGHT_GRAY);

        jBtnSaida.setBackground(Color.DARK_GRAY);
        jBtnSaida.setForeground(Color.LIGHT_GRAY);

        jBtnStart.setBackground(Color.DARK_GRAY);
        jBtnStart.setForeground(Color.LIGHT_GRAY);

        jBtnStop.setBackground(Color.DARK_GRAY);
        jBtnStop.setForeground(Color.LIGHT_GRAY);

        jBtnReset.setBackground(Color.DARK_GRAY);
        jBtnReset.setForeground(Color.LIGHT_GRAY);

    }

    private void setThemeLight() {

        jPanel1.setBackground(Color.LIGHT_GRAY);
        jPanel1.setForeground(Color.BLACK);

        jBtnRelogio.setBackground(Color.LIGHT_GRAY);
        jBtnRelogio.setForeground(Color.BLACK);

        jBtnAjuda.setBackground(Color.LIGHT_GRAY);
        jBtnAjuda.setForeground(Color.BLACK);

        jBtnSaida.setBackground(Color.LIGHT_GRAY);
        jBtnSaida.setForeground(Color.BLACK);

        jBtnMenu.setBackground(Color.LIGHT_GRAY);
        jBtnMenu.setForeground(Color.BLACK);

        jLblhora1.setForeground(Color.BLACK);
        jLblmili.setForeground(Color.BLACK);
        jLblminuto2.setForeground(Color.BLACK);
        jLblsegundo.setForeground(Color.BLACK);

        jBtnStart.setBackground(Color.LIGHT_GRAY);
        jBtnStart.setForeground(Color.BLACK);

        jBtnStop.setBackground(Color.LIGHT_GRAY);
        jBtnStop.setForeground(Color.BLACK);

        jBtnReset.setBackground(Color.LIGHT_GRAY);
        jBtnReset.setForeground(Color.BLACK);

    }

    private void setThemeGold() {

        jPanel1.setBackground(corFundo);
        jPanel1.setForeground(corLetras);

        jBtnRelogio.setBackground(corFundo);
        jBtnRelogio.setForeground(corLetras);

        jBtnAjuda.setBackground(corFundo);
        jBtnAjuda.setForeground(corLetras);

        jBtnSaida.setBackground(corFundo);
        jBtnSaida.setForeground(corLetras);

        jBtnMenu.setBackground(corFundo);
        jBtnMenu.setForeground(corLetras);

        jLblhora1.setForeground(corLetras);
        jLblmili.setForeground(corLetras);
        jLblminuto2.setForeground(corLetras);
        jLblsegundo.setForeground(corLetras);

        jBtnStart.setBackground(corFundo);
        jBtnStart.setForeground(corLetras);

        jBtnStop.setBackground(corFundo);
        jBtnStop.setForeground(corLetras);

        jBtnReset.setBackground(corFundo);
        jBtnReset.setForeground(corLetras);

    }


    private void jBtnRelogioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRelogioActionPerformed
        // TODO add your handling code here:

        // Instância de jFRelogio(Form de relógio)
        jF_Relogio FRelogio = new jF_Relogio() {
        };

        // Botão que abre o formulário jF_Relogio
        FRelogio.setVisible(true);

        // Fecha form Menu_TimeAPP
        this.dispose();

    }//GEN-LAST:event_jBtnRelogioActionPerformed

    private void jBtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMenuActionPerformed
        // TODO add your handling code here:

        // Menu_TimeApp MTAPP = new Menu_TimeApp();
        Menu_TimeApp MTAPP = new Menu_TimeApp() {
        };

        //  Botão que permite abrir o Menu
        MTAPP.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jBtnMenuActionPerformed

    private void jBtnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAjudaActionPerformed
        // TODO add your handling code here:

        // Instância de Form de Ajuda;
        jF_Ajuda ajuda = new jF_Ajuda();

        //  Botão que permite abrir o Formulario 
        ajuda.setVisible(true);

        // Fechar este formulário
        this.dispose();

    }//GEN-LAST:event_jBtnAjudaActionPerformed

    private void jBtnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaidaActionPerformed
        // TODO add your handling code here:

        // Fechar este formulário
        this.dispose();
    }//GEN-LAST:event_jBtnSaidaActionPerformed

    private void jBtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStartActionPerformed
        // TODO add your handling code here:

        state =true;
        
        // Dá inicio à contagem
        Thread t = new Thread() {
            @Override
            public void run() {
                for (;;) {
                    if (state == true) {
                        try {
                            sleep(1);

                            if (millisenconds > 1000) {
                                millisenconds = 0;
                                seconds++;
                            }
                            if (seconds > 60) {
                                millisenconds = 0;
                                seconds = 0;
                                minutes++;
                            }
                            if (minutes > 60) {
                                millisenconds = 0;
                                seconds = 0;
                                minutes = 0;
                                hour++;
                            }
                            millisenconds++;

                            jLblmili.setText(":" + verificaNumero(millisenconds));
                            jLblsegundo.setText(":" + verificaNumero(seconds));
                            jLblminuto2.setText(":" + verificaNumero(minutes));
                            jLblhora1.setText("" + verificaNumero(hour));

                        } catch (Exception e) {
                        }

                    } else {
                        state = false;
                        break;
                    }
                }

            }
        };
        t.start();

    }//GEN-LAST:event_jBtnStartActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        tema = utilitario.obtemTema();

        switch (tema) {
            case 0:
                setThemeLight();
                break;
            case 1:
                setThemeDark();
                break;
            default:
                setThemeGold();
                break;
        }


    }//GEN-LAST:event_formWindowGainedFocus

    private void jBtnSaidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSaidaMouseEntered
        // TODO add your handling code here:
        jBtnSaida.setBackground(Color.RED);
        jBtnSaida.setForeground(Color.WHITE);

    }//GEN-LAST:event_jBtnSaidaMouseEntered

    private void jBtnSaidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSaidaMouseExited
        // TODO add your handling code here:

        if (tema == 0) {
            jBtnSaida.setBackground(Color.LIGHT_GRAY);
            jBtnSaida.setForeground(Color.BLACK);
        } else if (tema == 1) {
            jBtnSaida.setBackground(Color.DARK_GRAY);
            jBtnSaida.setForeground(Color.LIGHT_GRAY);
        } else {
            jBtnSaida.setBackground(corFundo);
            jBtnSaida.setForeground(corLetras);
        }


    }//GEN-LAST:event_jBtnSaidaMouseExited

    private void jBtnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnStartMouseEntered
        // TODO add your handling code here:
        jBtnStart.setBackground(Color.GREEN);
        jBtnStart.setForeground(Color.BLACK);

    }//GEN-LAST:event_jBtnStartMouseEntered

    private void jBtnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnStartMouseExited
        // TODO add your handling code here:
        if (tema == 0) {
            jBtnStart.setBackground(Color.LIGHT_GRAY);
            jBtnStart.setForeground(Color.BLACK);
        } else if (tema == 1) {
            jBtnStart.setBackground(Color.DARK_GRAY);
            jBtnStart.setForeground(Color.LIGHT_GRAY);
        } else {
            jBtnStart.setBackground(corFundo);
            jBtnStart.setForeground(corLetras);
        }


    }//GEN-LAST:event_jBtnStartMouseExited

    private void jBtnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStopActionPerformed
        // TODO add your handling code here:
        state = false;

    }//GEN-LAST:event_jBtnStopActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
        state = false;
        millisenconds = 0;
        seconds = 0;
        minutes = 0;
        hour = 0;
        jLblmili.setText("00");
        jLblsegundo.setText("00");
        jLblminuto2.setText("00");
        jLblhora1.setText("00");

    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnStopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnStopMouseEntered
        // TODO add your handling code here:
        jBtnStop.setBackground(Color.RED);
        jBtnStop.setForeground(Color.BLACK);

    }//GEN-LAST:event_jBtnStopMouseEntered

    private void jBtnStopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnStopMouseExited
        // TODO add your handling code here:

        if (tema == 0) {
            jBtnStop.setBackground(Color.LIGHT_GRAY);
            jBtnStop.setForeground(Color.BLACK);
        } else if (tema == 1) {
            jBtnStop.setBackground(Color.DARK_GRAY);
            jBtnStop.setForeground(Color.LIGHT_GRAY);
        } else {
            jBtnStop.setBackground(corFundo);
            jBtnStop.setForeground(corLetras);
        }
    }//GEN-LAST:event_jBtnStopMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jF_Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jF_Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jF_Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jF_Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jF_Cronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAjuda;
    private javax.swing.JButton jBtnMenu;
    private javax.swing.JButton jBtnRelogio;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnSaida;
    private javax.swing.JButton jBtnStart;
    private javax.swing.JButton jBtnStop;
    private javax.swing.JLabel jLblhora1;
    private javax.swing.JLabel jLblmili;
    private javax.swing.JLabel jLblminuto2;
    private javax.swing.JLabel jLblsegundo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
