
import java.awt.Color;
import java.io.File;
import java.util.Calendar;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author 6487
 */
public abstract class jF_Relogio extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form jF_Relogio
     */
    //Instância de Form de Menu
    int hora, minutos, segundos;
    int dia, mes, ano, tema;
    String timestrt, yearstr;

    Color corFundo = new Color(153, 51, 0);
    Color corLetras = new Color(255, 153, 0);

    public jF_Relogio() {
        initComponents();
        Thread t = new Thread(this);
        t.start();
    }

    private void setThemeDark() {

        jPanel1.setBackground(Color.DARK_GRAY);
        jPanel1.setForeground(Color.LIGHT_GRAY);

        jLblData.setForeground(Color.LIGHT_GRAY);
        jLblTempo.setForeground(Color.LIGHT_GRAY);

        jBtn_Menu.setBackground(Color.DARK_GRAY);
        jBtn_Menu.setForeground(Color.LIGHT_GRAY);

        jBtn_Cronometro.setBackground(Color.DARK_GRAY);
        jBtn_Cronometro.setForeground(Color.LIGHT_GRAY);

        jBtn_Ajuda.setBackground(Color.DARK_GRAY);
        jBtn_Ajuda.setForeground(Color.LIGHT_GRAY);

        jBtnSaida.setBackground(Color.DARK_GRAY);
        jBtnSaida.setForeground(Color.LIGHT_GRAY);

        jBtn_Cronometro.setBackground(Color.DARK_GRAY);
        jBtn_Cronometro.setForeground(Color.LIGHT_GRAY);

    }

    private void setThemeLight() {

        jPanel1.setBackground(Color.LIGHT_GRAY);
        jPanel1.setForeground(Color.BLACK);

        jBtn_Cronometro.setBackground(Color.LIGHT_GRAY);
        jBtn_Cronometro.setForeground(Color.BLACK);

        jBtn_Ajuda.setBackground(Color.LIGHT_GRAY);
        jBtn_Ajuda.setForeground(Color.BLACK);

        jBtnSaida.setBackground(Color.LIGHT_GRAY);
        jBtnSaida.setForeground(Color.BLACK);

        jBtn_Menu.setBackground(Color.LIGHT_GRAY);
        jBtn_Menu.setForeground(Color.BLACK);

        jBtn_Cronometro.setBackground(Color.LIGHT_GRAY);
        jBtn_Cronometro.setForeground(Color.BLACK);

        jLblData.setForeground(Color.BLACK);
        jLblTempo.setForeground(Color.BLACK);

    }

    private void setThemeGold() {

        jPanel1.setBackground(corFundo);
        jPanel1.setForeground(corLetras);

        jBtn_Cronometro.setBackground(corFundo);
        jBtn_Cronometro.setForeground(corLetras);

        jBtn_Ajuda.setBackground(corFundo);
        jBtn_Ajuda.setForeground(corLetras);

        jBtnSaida.setBackground(corFundo);
        jBtnSaida.setForeground(corLetras);

        jBtn_Cronometro.setBackground(corFundo);
        jBtn_Cronometro.setForeground(corLetras);

        jBtn_Menu.setBackground(corFundo);
        jBtn_Menu.setForeground(corLetras);

        jLblTempo.setForeground(corLetras);
        jLblData.setForeground(corLetras);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtn_Cronometro = new javax.swing.JButton();
        jBtn_Menu = new javax.swing.JButton();
        jBtn_Ajuda = new javax.swing.JButton();
        jBtnSaida = new javax.swing.JButton();
        jLblTempo = new javax.swing.JLabel();
        jLblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jBtn_Cronometro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtn_Cronometro.setText("Cronometro");
        jBtn_Cronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CronometroActionPerformed(evt);
            }
        });

        jBtn_Menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtn_Menu.setText("Menu");
        jBtn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_MenuActionPerformed(evt);
            }
        });

        jBtn_Ajuda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtn_Ajuda.setText("Ajuda");
        jBtn_Ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AjudaActionPerformed(evt);
            }
        });

        jBtnSaida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnSaida.setText("Saída");
        jBtnSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSaidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSaidaMouseExited(evt);
            }
        });
        jBtnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaidaActionPerformed(evt);
            }
        });

        jLblTempo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLblTempo.setText("00:00:00");

        jLblData.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLblData.setText("21/12/1212");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jBtn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_Cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtn_Ajuda, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLblTempo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_Cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jBtn_Ajuda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLblData))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_MenuActionPerformed
        // TODO add your handling code here:

        // Menu_TimeApp MTAPP = new Menu_TimeApp();
        Menu_TimeApp MTAPP = new Menu_TimeApp();

        //  Botão que permite abrir o Menu
        MTAPP.setVisible(true);

        this.dispose();


    }//GEN-LAST:event_jBtn_MenuActionPerformed

    private void jBtn_CronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CronometroActionPerformed
        // TODO add your handling code here:

        // Instância de Form do Cronometro;
        jF_Cronometro Crono = new jF_Cronometro();

        //  Botão que permite abrir o Formulario 
        Crono.setVisible(true);

        // Fechar este formulário
        this.dispose();

    }//GEN-LAST:event_jBtn_CronometroActionPerformed

    private void jBtn_AjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AjudaActionPerformed
        // TODO add your handling code here:

        // Instância de Form de Ajuda;
        jF_Ajuda ajuda = new jF_Ajuda();

        //  Botão que permite abrir o Formulario 
        ajuda.setVisible(true);

        // Fechar este formulário
        this.dispose();

    }//GEN-LAST:event_jBtn_AjudaActionPerformed

    private void jBtnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaidaActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_jBtnSaidaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        Scanner scanner = null;

        try {
            scanner = new Scanner(new File("tema.txt"));

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            System.out.println(line);
            tema = Integer.parseInt(line);

        }

        switch (tema) {
            case 0:
                setThemeLight();
                break;
            case 1:
                setThemeDark();
                break;
            default:
                setThemeGold();
                break;
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jBtnSaidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSaidaMouseEntered
        // TODO add your handling code here:
        jBtnSaida.setBackground(Color.RED);
        jBtnSaida.setForeground(Color.WHITE);

    }//GEN-LAST:event_jBtnSaidaMouseEntered

    private void jBtnSaidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSaidaMouseExited
        // TODO add your handling code here:
        if (tema == 0) {
            jBtnSaida.setBackground(Color.LIGHT_GRAY);
            jBtnSaida.setForeground(Color.BLACK);
        } else if (tema == 1) {
            jBtnSaida.setBackground(Color.DARK_GRAY);
            jBtnSaida.setForeground(Color.LIGHT_GRAY);
        } else {
            jBtnSaida.setBackground(corFundo);
            jBtnSaida.setForeground(corLetras);
        }
    }//GEN-LAST:event_jBtnSaidaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jF_Relogio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jF_Relogio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jF_Relogio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jF_Relogio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new jF_Relogio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSaida;
    private javax.swing.JButton jBtn_Ajuda;
    private javax.swing.JButton jBtn_Cronometro;
    private javax.swing.JButton jBtn_Menu;
    private javax.swing.JLabel jLblData;
    private javax.swing.JLabel jLblTempo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {

            try {
                Calendar c = Calendar.getInstance();
                hora = c.get(Calendar.HOUR_OF_DAY);
                minutos = c.get(Calendar.MINUTE);
                segundos = c.get(Calendar.SECOND);
                ano = c.get(Calendar.YEAR);
                mes = c.get(Calendar.MONTH);
                dia = c.get(Calendar.DAY_OF_MONTH);

                jLblTempo.setText("" + hora + ":" + minutos + ":" + segundos);
                jLblData.setText("" + dia + ":" + mes + ":" + ano);

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
