/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 6487 || Noémio Dória
 */
public class Calculator_full extends javax.swing.JFrame {

    /**
     * Creates new form Calculator_full
     */
    
    double NEnter1; // Número para a 1a parcela
    double NEnter2; // Número para a 2a parcela
    double NResult; // Número para o Resultado
    String op; // Operação a efectuar
    
    public Calculator_full() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBTN0 = new javax.swing.JButton();
        jBTBackSpace = new javax.swing.JButton();
        jBTN7 = new javax.swing.JButton();
        jBTN4 = new javax.swing.JButton();
        jBTN1 = new javax.swing.JButton();
        jBTDot = new javax.swing.JButton();
        jBTCE = new javax.swing.JButton();
        jBTN8 = new javax.swing.JButton();
        jBTN5 = new javax.swing.JButton();
        jBTN2 = new javax.swing.JButton();
        jBTEqual = new javax.swing.JButton();
        jBTClear = new javax.swing.JButton();
        jBTN9 = new javax.swing.JButton();
        jBTN6 = new javax.swing.JButton();
        jBTN3 = new javax.swing.JButton();
        jBTDivide = new javax.swing.JButton();
        jBTPlusMinus = new javax.swing.JButton();
        jBTPlus = new javax.swing.JButton();
        jBTMinus = new javax.swing.JButton();
        jBTMultiply = new javax.swing.JButton();
        jTF_Resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBTN0.setBackground(new java.awt.Color(51, 51, 51));
        jBTN0.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN0.setForeground(new java.awt.Color(204, 204, 204));
        jBTN0.setText("0");
        jBTN0.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jBTBackSpace.setBackground(new java.awt.Color(51, 51, 51));
        jBTBackSpace.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBTBackSpace.setForeground(new java.awt.Color(204, 204, 204));
        jBTBackSpace.setText("←");
        jBTBackSpace.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTBackSpaceActionPerformed(evt);
            }
        });
        getContentPane().add(jBTBackSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jBTN7.setBackground(new java.awt.Color(51, 51, 51));
        jBTN7.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN7.setForeground(new java.awt.Color(204, 204, 204));
        jBTN7.setText("7");
        jBTN7.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jBTN4.setBackground(new java.awt.Color(51, 51, 51));
        jBTN4.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN4.setForeground(new java.awt.Color(204, 204, 204));
        jBTN4.setText("4");
        jBTN4.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jBTN1.setBackground(new java.awt.Color(51, 51, 51));
        jBTN1.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN1.setForeground(new java.awt.Color(204, 204, 204));
        jBTN1.setText("1");
        jBTN1.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jBTDot.setBackground(new java.awt.Color(51, 51, 51));
        jBTDot.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTDot.setForeground(new java.awt.Color(204, 204, 204));
        jBTDot.setText(".");
        jBTDot.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTDotActionPerformed(evt);
            }
        });
        getContentPane().add(jBTDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jBTCE.setBackground(new java.awt.Color(51, 51, 51));
        jBTCE.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTCE.setForeground(new java.awt.Color(204, 204, 204));
        jBTCE.setText("CE");
        jBTCE.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCEActionPerformed(evt);
            }
        });
        getContentPane().add(jBTCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jBTN8.setBackground(new java.awt.Color(51, 51, 51));
        jBTN8.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN8.setForeground(new java.awt.Color(204, 204, 204));
        jBTN8.setText("8");
        jBTN8.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jBTN5.setBackground(new java.awt.Color(51, 51, 51));
        jBTN5.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN5.setForeground(new java.awt.Color(204, 204, 204));
        jBTN5.setText("5");
        jBTN5.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jBTN2.setBackground(new java.awt.Color(51, 51, 51));
        jBTN2.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN2.setForeground(new java.awt.Color(204, 204, 204));
        jBTN2.setText("2");
        jBTN2.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jBTEqual.setBackground(new java.awt.Color(51, 51, 51));
        jBTEqual.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTEqual.setForeground(new java.awt.Color(204, 204, 204));
        jBTEqual.setText("=");
        jBTEqual.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jBTEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jBTClear.setBackground(new java.awt.Color(51, 51, 51));
        jBTClear.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTClear.setForeground(new java.awt.Color(204, 204, 204));
        jBTClear.setText("C");
        jBTClear.setPreferredSize(new java.awt.Dimension(75, 75));
        getContentPane().add(jBTClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jBTN9.setBackground(new java.awt.Color(51, 51, 51));
        jBTN9.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN9.setForeground(new java.awt.Color(204, 204, 204));
        jBTN9.setText("9");
        jBTN9.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jBTN6.setBackground(new java.awt.Color(51, 51, 51));
        jBTN6.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN6.setForeground(new java.awt.Color(204, 204, 204));
        jBTN6.setText("6");
        jBTN6.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jBTN3.setBackground(new java.awt.Color(51, 51, 51));
        jBTN3.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTN3.setForeground(new java.awt.Color(204, 204, 204));
        jBTN3.setText("3");
        jBTN3.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBTN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jBTDivide.setBackground(new java.awt.Color(51, 51, 51));
        jBTDivide.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTDivide.setForeground(new java.awt.Color(204, 204, 204));
        jBTDivide.setText("/");
        jBTDivide.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jBTDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        jBTPlusMinus.setBackground(new java.awt.Color(51, 51, 51));
        jBTPlusMinus.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTPlusMinus.setForeground(new java.awt.Color(204, 204, 204));
        jBTPlusMinus.setText("±");
        jBTPlusMinus.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTPlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBTPlusMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jBTPlus.setBackground(new java.awt.Color(51, 51, 51));
        jBTPlus.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTPlus.setForeground(new java.awt.Color(204, 204, 204));
        jBTPlus.setText("+");
        jBTPlus.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jBTPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jBTMinus.setBackground(new java.awt.Color(51, 51, 51));
        jBTMinus.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTMinus.setForeground(new java.awt.Color(204, 204, 204));
        jBTMinus.setText("-");
        jBTMinus.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBTMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jBTMultiply.setBackground(new java.awt.Color(51, 51, 51));
        jBTMultiply.setFont(new java.awt.Font("Eurostile", 0, 24)); // NOI18N
        jBTMultiply.setForeground(new java.awt.Color(204, 204, 204));
        jBTMultiply.setText("X");
        jBTMultiply.setPreferredSize(new java.awt.Dimension(75, 75));
        jBTMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(jBTMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jTF_Resultado.setBackground(new java.awt.Color(255, 204, 51));
        jTF_Resultado.setFont(new java.awt.Font("Digital-7 Mono", 0, 48)); // NOI18N
        jTF_Resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTF_Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN6ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("6");
    }//GEN-LAST:event_jBTN6ActionPerformed

    private void jBTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN7ActionPerformed
        // TODO add your handling code here:
        //Método criado automaticamente clicando 2 vezes no botão.
        EnterNumbers("7");
        
    }//GEN-LAST:event_jBTN7ActionPerformed

    private void jBTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN8ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_jBTN8ActionPerformed

    private void jBTN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN9ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("9");
    }//GEN-LAST:event_jBTN9ActionPerformed

    private void jBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN4ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("4");
    }//GEN-LAST:event_jBTN4ActionPerformed

    private void jBTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN5ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("5");
    }//GEN-LAST:event_jBTN5ActionPerformed

    private void jBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN1ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
    }//GEN-LAST:event_jBTN1ActionPerformed

    private void jBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN2ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("2");
    }//GEN-LAST:event_jBTN2ActionPerformed

    private void jBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN3ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("3");
    }//GEN-LAST:event_jBTN3ActionPerformed

    private void jBTN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN0ActionPerformed
         // TODO add your handling code here:
         EnterNumbers("0");
    }//GEN-LAST:event_jBTN0ActionPerformed

    private void jBTDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTDivideActionPerformed
        // TODO add your handling code here:
        NEnter1 = Double.parseDouble(jTF_Resultado.getText());
        jTF_Resultado.setText("");    
        op="/";
     
        
        
    }//GEN-LAST:event_jBTDivideActionPerformed

    private void jBTMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTMultiplyActionPerformed
        // TODO add your handling code here:
        NEnter1 = Double.parseDouble(jTF_Resultado.getText());
        jTF_Resultado.setText("");    
        op="*";
    }//GEN-LAST:event_jBTMultiplyActionPerformed

    private void jBTMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTMinusActionPerformed
        // TODO add your handling code here:
        NEnter1 = Double.parseDouble(jTF_Resultado.getText());
        jTF_Resultado.setText("");    
        op="-";
    }//GEN-LAST:event_jBTMinusActionPerformed

    private void jBTPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTPlusActionPerformed
        // TODO add your handling code here:
        NEnter1 = Double.parseDouble(jTF_Resultado.getText());
        jTF_Resultado.setText("");    
        op="+";
    }//GEN-LAST:event_jBTPlusActionPerformed

    private void jBTCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCEActionPerformed
        // TODO add your handling code here:
        jTF_Resultado.setText("");          
        String Fn,Sn;
        Fn = String.valueOf(NEnter1);
        Sn = String.valueOf(NEnter2);
        Fn ="";
        Sn ="";
    }//GEN-LAST:event_jBTCEActionPerformed

    private void jBTPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTPlusMinusActionPerformed
        // TODO add your handling code here:
        double nums = Double.parseDouble(String.valueOf(jTF_Resultado.getText())); 
        nums = nums*-1;
        jTF_Resultado.setText(String.valueOf(nums));
    }//GEN-LAST:event_jBTPlusMinusActionPerformed

    private void jBTBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTBackSpaceActionPerformed
        // TODO add your handling code here:
        
        if(jTF_Resultado.getText().length()>0)
        {
            String backSp;
            StringBuilder sb = new StringBuilder(jTF_Resultado.getText());
            sb.deleteCharAt(jTF_Resultado.getText().length()-1);
            backSp = sb.toString();
            jTF_Resultado.setText(backSp);
        }
        
        
    }//GEN-LAST:event_jBTBackSpaceActionPerformed

    private void jBTDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTDotActionPerformed
        // TODO add your handling code here:
        //Se não contiver ponto vai inserir ponto
        if (! jTF_Resultado.getText().contains("."))
        {
            jTF_Resultado.setText(jTF_Resultado.getText()+jBTDot.getText());
        }
    }//GEN-LAST:event_jBTDotActionPerformed

    private void jBTEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTEqualActionPerformed
        // TODO add your handling code here:
        NEnter2 = Double.parseDouble(jTF_Resultado.getText());
        
        if (op=="+")
        {
            NResult = NEnter1+NEnter2;
            jTF_Resultado.setText(String.valueOf(NResult));
        }
         else if (op=="-")
        {
            NResult = NEnter1-NEnter2;
            jTF_Resultado.setText(String.valueOf(NResult));
        }
        else if (op=="*")
        {
            NResult = NEnter1*NEnter2;
            jTF_Resultado.setText(String.valueOf(NResult));
        }
        else if (op=="/")
        {
            NResult = NEnter1/NEnter2;
            jTF_Resultado.setText(String.valueOf(NResult));
        }
        
        
        
        
    }//GEN-LAST:event_jBTEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_full.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_full.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_full.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_full.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_full().setVisible(true);
            }
        });
    }

    private void EnterNumbers(String q) //Feito pelo autor
    {
        //Método que trata a entrada de números
            String Nums = jTF_Resultado.getText()+q;
            jTF_Resultado.setText(Nums);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTBackSpace;
    private javax.swing.JButton jBTCE;
    private javax.swing.JButton jBTClear;
    private javax.swing.JButton jBTDivide;
    private javax.swing.JButton jBTDot;
    private javax.swing.JButton jBTEqual;
    private javax.swing.JButton jBTMinus;
    private javax.swing.JButton jBTMultiply;
    private javax.swing.JButton jBTN0;
    private javax.swing.JButton jBTN1;
    private javax.swing.JButton jBTN2;
    private javax.swing.JButton jBTN3;
    private javax.swing.JButton jBTN4;
    private javax.swing.JButton jBTN5;
    private javax.swing.JButton jBTN6;
    private javax.swing.JButton jBTN7;
    private javax.swing.JButton jBTN8;
    private javax.swing.JButton jBTN9;
    private javax.swing.JButton jBTPlus;
    private javax.swing.JButton jBTPlusMinus;
    private javax.swing.JTextField jTF_Resultado;
    // End of variables declaration//GEN-END:variables
}
